# -------------------------------------------------------
#  _                  _                  _
# | | __ _ _____   _ | |_ ___  _ __ ___ | |
# | |/ _` |_  / | | || __/ _ \| '_ ` _ \| |
# | | (_| |/ /| |_| || || (_) | | | | | | |
# |_|\__,_/___|\__, (_)__\___/|_| |_| |_|_|
#              |___/
# -------------------------------------------------------

# -------------------------------------------------------
# Dein.vim command
# -------------------------------------------------------

[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

