# -------------------------------------------------------
#        _             _            _                  _
#  _ __ | |_   _  __ _(_)_ __  ___ | |_ ___  _ __ ___ | |
# | '_ \| | | | |/ _` | | '_ \/ __|| __/ _ \| '_ ` _ \| |
# | |_) | | |_| | (_| | | | | \__ \| || (_) | | | | | | |
# | .__/|_|\__,_|\__, |_|_| |_|___(_)__\___/|_| |_| |_|_|
# |_|            |___/
# -------------------------------------------------------

# -------------------------------------------------------
# Dein
# -------------------------------------------------------

[[plugins]]
 repo = 'Shougo/dein.vim'

# -------------------------------------------------------
# Colorscheme
# -------------------------------------------------------

[[plugins]]
 repo = "joshdick/onedark.vim"

[[plugins]]
 repo = 'itchyny/lightline.vim'
 hook_add = '''
     let g:lightline = { 'colorscheme': 'onedark' }
 '''

# -------------------------------------------------------
# Completion
# -------------------------------------------------------

# ---------- ddc && pum ----------

[[plugins]]
 repo = "Shougo/ddc.vim"
 hook_add = '''
     source ~/.config/nvim/dein/config/ddc.vim
 '''

[[plugins]]
 repo = "Shougo/pum.vim"

# denops (depended for ddc.vim)
[[plugins]]
 repo = "vim-denops/denops.vim"

# ddc-plugins
[[plugins]]
 repo = "Shougo/ddc-nvim-lsp"

[[plugins]]
 repo = "Shougo/ddc-around"

[[plugins]]
repo = 'tani/ddc-fuzzy'

# [[plugins]]
# repo = 'iamcco/markdown-preview.nvim'
# build = 'cd app && yarn install'
# hook_add = '''
#     let g:mkdp_auto_start = 1
#     let g:mkdp_auto_close = 1
#     let g:mkdp_browser = 'firefox'
#     let g:mkdp_command_for_global = 1
# '''

[[plugins]]
 repo = "matsui54/denops-popup-preview.vim"
 hook_add = '''
   call popup_preview#enable()
 '''

[[plugins]]
 repo = "matsui54/denops-signature_help"
 hook_add = '''
   call signature_help#enable()
   let g:signature_help_config = { 'border': v:true, 'style': 'full' }
 '''

# ---------- nvim-lsp ----------

[[plugins]]
 repo = 'neovim/nvim-lspconfig'
 hook_add = '''
     source ~/.config/nvim/dein/config/nvim-lspconfig.vim
 '''

[[plugins]]
 repo = "williamboman/nvim-lsp-installer"

# ---------- tree-sitter ----------

[[plugins]]
 repo = 'nvim-treesitter/nvim-treesitter'
 hook_add = '''
     source ~/.config/nvim/dein/config/nvim-treesitter.vim
 '''

# ---------- snippets ----------

[[plugins]]
 repo = 'hrsh7th/vim-vsnip'
 hook_add = '''
     source ~/.config/nvim/dein/config/vim-vsnip.vim
 '''

[[plugins]]
 repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
 repo = 'rafamadriz/friendly-snippets'

# -------------------------------------------------------
# LaTeX
# -------------------------------------------------------

# ---------- vimtex ----------

[[plugins]]
 repo = 'lervag/vimtex'
 hook_add = '''
     let g:vimtex_view_method = 'zathura'
 '''

# -------------------------------------------------------
# Markdown
# -------------------------------------------------------

[[plugins]]
 repo = 'iamcco/markdown-preview.nvim'
 build = 'cd app && yarn install'
 hook_add = '''
     let g:mkdp_auto_start = 1
     let g:mkdp_auto_close = 1
     let g:mkdp_browser = 'firefox'
     let g:mkdp_command_for_global = 1
 '''

# -------------------------------------------------------
# Filer
# -------------------------------------------------------

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
    source ~/.config/nvim/dein/config/defx.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 't9md/vim-choosewin'
hook_add = '''
    let g:choosewin_overlay_enabled = 1
    let g:choosewin_overlay_clear_multibyte = 1
'''

# -------------------------------------------------------
# Terminal
# -------------------------------------------------------

[[plugins]]
 repo = 'Shougo/deol.nvim'
 hook_add = '''
     nnoremap <silent><C-o> :<C-u>Deol -split=floating<CR>
     tnoremap <ESC>   <C-\><C-n>
 '''
