# -------------------------------------------------------
#        _             _            _                  _
#  _ __ | |_   _  __ _(_)_ __  ___ | |_ ___  _ __ ___ | |
# | '_ \| | | | |/ _` | | '_ \/ __|| __/ _ \| '_ ` _ \| |
# | |_) | | |_| | (_| | | | | \__ \| || (_) | | | | | | |
# | .__/|_|\__,_|\__, |_|_| |_|___(_)__\___/|_| |_| |_|_|
# |_|            |___/
# -------------------------------------------------------

# -------------------------------------------------------
# Dein
# -------------------------------------------------------

[[plugins]]
 repo = 'Shougo/dein.vim'

# -------------------------------------------------------
# Colorscheme / Icon
# -------------------------------------------------------

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set termguicolors
  set background=dark
  colorscheme iceberg
'''

[[plugins]]
 repo = 'itchyny/lightline.vim'
 hook_add = '''
  let g:lightline = { 'colorscheme': 'iceberg' }
 '''

[[plugins]]
 repo = "kyazdani42/nvim-web-devicons"

[[plugins]]
 repo = "mhinz/vim-startify"

# -------------------------------------------------------
# Completion
# -------------------------------------------------------

# ---------- coc-nvim ----------

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
    source ~/.config/nvim/dein/config/coc.nvim
'''

# ---------- snippets ----------

[[plugins]]
repo = 'honza/vim-snippets'

# ---------- tree-sitter ----------

[[plugins]]
 repo = 'nvim-treesitter/nvim-treesitter'
 hook_add = '''
     source ~/.config/nvim/dein/config/nvim-treesitter.vim
 '''

# -------------------------------------------------------
# LaTeX
# -------------------------------------------------------

# ---------- vimtex ----------

[[plugins]]
 repo = 'lervag/vimtex'
 hook_add = '''
     let g:vimtex_view_method = 'skim'
 '''

# -------------------------------------------------------
# Markdown
# -------------------------------------------------------

[[plugins]]
 repo = 'iamcco/markdown-preview.nvim'
 build = 'cd app && yarn install'
 hook_add = '''
     function OpenMarkdownPreview (url)
       execute "silent ! /Applications/Firefox.app/Contents/MacOS/firefox --new-window " . a:url
     endfunction
     let g:mkdp_browserfunc = 'OpenMarkdownPreview'

     let g:mkdp_auto_start = 1
     let g:mkdp_auto_close = 1
     let g:mkdp_command_for_global = 1
 '''

# -------------------------------------------------------
# Filer
# -------------------------------------------------------

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
    source ~/.config/nvim/dein/config/defx.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 't9md/vim-choosewin'
hook_add = '''
    let g:choosewin_overlay_enabled = 1
    let g:choosewin_overlay_clear_multibyte = 1
'''

# -------------------------------------------------------
# Git
# -------------------------------------------------------

[[plugins]]
 repo = 'nvim-lua/plenary.nvim'

[[plugins]]
 repo = 'lewis6991/gitsigns.nvim'
 hook_add = '''
     source ~/.config/nvim/dein/config/gitsigns.vim
 '''

# -------------------------------------------------------
# Terminal
# -------------------------------------------------------

[[plugins]]
 repo = 'Shougo/deol.nvim'
 hook_add = '''
     nnoremap <silent><C-o> :<C-u>Deol -split=floating<CR>
     tnoremap <ESC>   <C-\><C-n>
 '''
