# Dein
[[plugins]]
repo = 'Shougo/dein.vim'

# Completion
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'Yggdroot/indentLine'

# Appearance
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'edkolev/tmuxline.vim'
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
'''

# LaTeX
[[plugins]]
repo = 'lervag/vimtex'

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
