# Dein
[[plugins]]
repo = 'Shougo/dein.vim'

# Completion
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'Yggdroot/indentLine'

# snippet
[[plugins]]
repo = 'Shougo/neocomplete.vim'
[[plugins]]
repo = 'Shougo/neocomplcache.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'shougo/neosnippet-snippets'

# Appearance
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'edkolev/tmuxline.vim'
[[plugins]]
repo = 'itchyny/lightline.vim'

# Git
[[plugins]]
repo = "airblade/vim-gitgutter"
[[plugins]]
repo = "tpope/vim-fugitive"


# LaTeX
[[plugins]]
repo = 'lervag/vimtex'

# yaml
[[plugins]]
repo = 'chase/vim-ansible-yaml'

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
