name: linux

on:
  push:
  pull_request:

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Error Check
    - name: Run init.sh
      run: ${GITHUB_WORKSPACE}/bin/install.sh

